# Generated by Django 5.0.7 on 2024-07-21 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_messages_number_for_first', models.IntegerField(default=0)),
                ('new_messages_number_for_second', models.IntegerField(default=0)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encrypted_message', models.TextField(max_length=4096)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted_for_receiver', models.BooleanField(default=False)),
                ('is_deleted_for_sender', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encmessages.personalchat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='personalchat',
            name='last_message',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='encmessages.personalmessage'),
        ),
    ]
