# Generated by Django 5.0.7 on 2024-07-19 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encprofiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_user', models.ManyToManyField(to='encprofiles.user')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.DateTimeField(auto_now_add=True)),
                ('encrypted_message', models.TextField(max_length=4096)),
                ('changed', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Normal'), (1, 'Deleted On Sender Side'), (2, 'Deleted On Receiver Side'), (3, 'Deleted')], default=0)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encmessages.personalchat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encprofiles.user')),
            ],
        ),
    ]
