# Generated by Django 5.0.7 on 2024-07-19 12:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=61)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('is_shown_phone', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_shown_email', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=63)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Off')], default=1)),
                ('last_seen', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
