# Generated by Django 5.0.7 on 2024-07-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Off')], default=1)),
                ('last_seen', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
